name: Dev CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Remove prepare
        run: npm pkg delete scripts.prepare

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run ci:lint

      - name: Typechecking
        run: npm run typecheck
