name: Release

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Default commit message'
        default: 'Merge development → main'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout main
        run: git checkout main

      - name: Merge development into main
        run: |
          git fetch origin development
          git merge --no-ff origin/development -m "${{ github.event.inputs.commit_message }}"

      - name: Push to main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: git push https://x-access-token:${PAT_TOKEN}@github.com/lcs-franco/ghibli-wiki.git main
